#THIS CONFIG FILE CONTAINS ALL PARAMETERIZABLE VARIABLES WITH DEFAULT VALUES,
#most of them are kwargs in the respecitve inits, so they can be left out of the config file,
# but they are listed here for reference.
seed:
   123
n_cpus: #number of cpus used
   10
env_config:
   n: 8 #size of board
   goal_length: 5 #length of correct path (e.g. 4 means goal can be unlocked with 3rd key), can be list
   num_distractor: 2 #number of distractor branches, can be list
   distractor_length: 2 #length/"depth" of each distractor branch, can be list
   step_cost: 0  #reward structure
   reward_gem: 10
   reward_dead: 0
   reward_correct_key: 1
   reward_wrong_key: -1,
   max_steps: 3000 #maximum number of steps before environment terminates
   verbose: False
net_config:
   att_emb_size: 64
   n_heads: 2
   n_att_stack: 2
   n_fc_layers: 4
   pad: True #padding will maintain size of state space
gamma: #temporal discount factor
   0.99
n_step: #number of a2c updates, i.e. number of episodes each worker samples
   10
optimizer:
   Adam #RMSprop #or Adam
lr:
   0.00001
tensorboard:
   False
plot:
   False